[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
# Override the Solidity version (this overrides `auto_detect_solc`)
solc_version = '0.8.20'
via_ir = true
optimizer = true
optimizer_runs = 200
verbosity = 4

# Add caching settings
cache = true
cache_path = 'cache'

# Optional: Force cache invalidation only when source files change
force_cache = true

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.fast]
via_ir = false
optimizer = false
verbosity = 2
