[profile.default]
src = "src"
out = "out"
ffi = true
build_info = true
ast = true
extra_output = ["storageLayout", "abi", "metadata", "devdoc", "userdoc"]
libs = ["lib"]
gas_reports = ["*"]
solc_version = '0.8.28'

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.fast]
via_ir = false
optimizer = false
verbosity = 2
